include:
  - component: $CI_SERVER_FQDN/devops/ci-cd-components/php-quality@v1.6.0
    inputs:
      extra_system_packages: "libonig-dev libsqlite3-dev"
      php_extensions: "zip mbstring pdo_sqlite sockets"
      lint_commands:
        - vendor/bin/phpcs --standard=PSR12 --extensions=php src tests
      test_commands:
        - vendor/bin/phpunit --configuration ./phpunit.xml.dist --testsuite Unit --no-coverage
        - vendor/bin/phpunit --configuration ./phpunit.xml.dist --testsuite Integration --no-coverage
        - vendor/bin/phpunit --configuration ./phpunit.xml.dist --testsuite Functional --no-coverage
