variables:
  COMPOSER_CACHE_DIR: "$CI_PROJECT_DIR/.composer-cache"

cache:
  paths:
    - .composer-cache/
    - vendor/

.php_template: &php_template
  image: php:8.3-cli
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq git unzip libzip-dev zlib1g-dev libxml2-dev pkg-config build-essential autoconf libssl-dev
    - docker-php-ext-install zip sockets
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install --no-progress --no-interaction --prefer-dist

lint:phpcs:
  <<: *php_template
  stage: test
  script:
    - vendor/bin/phpcs --standard=PSR12 --extensions=php src tests

test:phpunit:
  <<: *php_template
  stage: test
  script:
    - vendor/bin/phpunit --configuration ./phpunit.xml.dist --testsuite Unit --no-coverage
    - vendor/bin/phpunit --configuration ./phpunit.xml.dist --testsuite Integration --no-coverage
