services:
  hat-app:
    image: ghcr.io/evilprophet/homelab-assistant-tool:latest
    container_name: hat-app
    volumes:
      - ./var/data:/app/var/data
      - ./var/log:/app/var/log
    env_file:
      - .env
    network_mode: host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
