services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      string $applicationDirectory: '%kernel.project_dir%'
      string $sqliteDatabasePath: '%sqlite_database_path%'
      array $configuration: '%configuration%'
      Psr\Log\LoggerInterface $webLogger: '@monolog.logger.web'

  EvilStudio\HAT\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  Symfony\Component\Filesystem\Filesystem: ~

  EvilStudio\HAT\Service\Infrastructure\SqlitePragmaMiddleware:
    tags:
      - { name: doctrine.middleware }
